/*

.-----------------------------------------------------------------------------.
| The Chatting Zone (TCZ)                            (C) J.P.Boggis 1993-2004 |
| ~~~~~~~~~~~~~~~~~~~~~~~                            ~~~~~~~~~~~~~~~~~~~~~~~~ |
|-----------------------------------------------------------------------------|
| AT_CMDTABLE.H  -  Table of '@' commands.                                    |
|--------------------------[ Copyright Information ]--------------------------|
| This program is free software; you can redistribute it and/or modify        |
| it under the terms of the GNU General Public License as published by        |
| the Free Software Foundation; either version 2 of the License, or           |
| (at your option) any later version.                                         |
|                                                                             |
| This program is distributed in the hope that it will be useful,             |
| but WITHOUT ANY WARRANTY; without even the implied warranty of              |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               |
| GNU General Public License for more details.                                |
|                                                                             |
| You should have received a copy of the GNU General Public License           |
| along with this program; if not, write to the Free Software                 |
| Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA   |
|-----------------------[ Credits & Acknowledgements ]------------------------|
| For full details of authors and contributers to TCZ, please see the files   |
| MODULES and CONTRIBUTERS.  For copyright and license information, please    |
| see LICENSE and COPYRIGHT.                                                  |
|                                                                             |
| Module originally designed and written by:  J.P.Boggis 03/06/1999.          |
|-------------------------[ The Chatting Zone (TCZ) ]-------------------------|
|                For more information about TCZ, please visit:                |
|                   http://www.sourceforge.net/projects/tcz                   |
`-----------------------------------------------------------------------------'

  $Id: at_cmdtable.h,v 1.1.1.1 2004/12/02 17:43:11 jpboggis Exp $

*/


/* ---->  '@' command table  <---- */
struct cmd_table at_cmds[] = {
       {AT_COMMAND,    "@",                      (void *) look_notice,               10, 0, 0},
       {AT_COMMAND,    "@admin",                 (void *) admin_options,             0, 0, 0},
       {AT_COMMAND,    "@administration",        (void *) admin_options,             0, 0, 0},
       {AT_COMMAND,    "@administrative",        (void *) admin_options,             0, 0, 0},
       {AT_COMMAND,    "@alarm",                 (void *) create_alarm,              0, 0, 0},
       {AT_COMMAND,    "@alias",                 (void *) alias_alias,               0, 0, 0},
       {AT_COMMAND,    "@areaname",              (void *) set_areaname,              0, 0, 0},
       {AT_COMMAND,    "@areawrite",             (void *) comms_areawrite,           0, 0, 0},
       {AT_COMMAND,    "@array",                 (void *) create_array,              0, 0, 0},
       {AT_COMMAND,    "@attr",                  (void *) combat_statistics,         0, 0, 0},
       {AT_COMMAND,    "@attributes",            (void *) combat_statistics,         0, 0, 0},
       {AT_COMMAND,    "@ban",                   (void *) admin_ban,                 0, 0, 0},
       {AT_COMMAND,    "@banish",                (void *) banish_main,               0, 0, 0},
       {AT_COMMAND,    "@banishname",            (void *) banish_main,               0, 0, 0},
       {AT_COMMAND,    "@begin",                 (void *) selection_begin,           0, 0, 0},
       {AT_COMMAND,    "@beep",                  (void *) comms_beep,                0, 0, 0},
       {AT_COMMAND,    "@boot",                  (void *) admin_boot,                0, 0, 0},
       {AT_COMMAND,    "@bootdead",              (void *) admin_bootdead,            0, 0, 0},
       {AT_COMMAND,    "@break",                 (void *) selection_return_break,    1, 0, 0},
       {AT_COMMAND,    "@breakloop",             (void *) selection_breakloop,       0, 0, 0},
       {QUERY_COMMAND, "@calc",                  (void *) calculate_evaluate,        0, 0, 0},
       {QUERY_COMMAND, "@calculate",             (void *) calculate_evaluate,        0, 0, 0},
       {AT_COMMAND,    "@case",                  (void *) selection_case,            0, 0, 0},
       {AT_COMMAND,    "@casefirst",             (void *) selection_case,            1, 0, 0},
       {AT_COMMAND,    "@caserandom",            (void *) selection_case,            2, 0, 0},
       {AT_COMMAND,    "@censor",                (void *) comms_censor,              0, 0, 0},
       {AT_COMMAND,    "@censored",              (void *) comms_censor,              0, 0, 0},
       {AT_COMMAND,    "@censorship",            (void *) comms_censor,              0, 0, 0},
       {AT_COMMAND,    "@cfail",                 (void *) command_csucc_or_cfail,    0, 0, 0},
       {AT_COMMAND,    "@cfailure",              (void *) command_csucc_or_cfail,    0, 0, 0},
       {AT_COMMAND,    "@char",                  (void *) create_character,          0, 0, 0},
       {AT_COMMAND,    "@character",             (void *) create_character,          0, 0, 0},
       {AT_COMMAND,    "@chown",                 (void *) set_owner,                 0, 0, 0},
       {AT_COMMAND,    "@chownership",           (void *) set_owner,                 0, 0, 0},
       {AT_COMMAND,    "@chpid",                 (void *) command_chpid,             0, 0, 0},
       {AT_COMMAND,    "@chuid",                 (void *) command_chuid,             0, 0, 0},
       {AT_COMMAND,    "@com",                   (void *) create_command,            0, 0, 0},
       {AT_COMMAND,    "@comm",                  (void *) create_command,            0, 0, 0},
       {AT_COMMAND,    "@command",               (void *) create_command,            0, 0, 0},
       {AT_COMMAND,    "@cont",                  (void *) stats_contents,            0, 0, 0},
       {AT_COMMAND,    "@contents",              (void *) stats_contents,            0, 0, 0},
       {AT_COMMAND,    "@continue",              (void *) selection_continue,        0, 0, 0},
       {AT_COMMAND,    "@controller",            (void *) admin_controller,          0, 0, 0},
       {AT_COMMAND,    "@count",                 (void *) stats_contents,            0, 0, 0},
       {AT_COMMAND,    "@create",                (void *) create_thing,              0, 0, 0},
       {AT_COMMAND,    "@credit",                (void *) finance_credit,            0, 0, 0},
       {AT_COMMAND,    "@credits",               (void *) finance_credit,            0, 0, 0},
       {AT_COMMAND,    "@cstr",                  (void *) set_cstring,               0, 0, 0},
       {AT_COMMAND,    "@cstring",               (void *) set_cstring,               0, 0, 0},
       {AT_COMMAND,    "@csucc",                 (void *) command_csucc_or_cfail,    1, 0, 0},
       {AT_COMMAND,    "@csuccess",              (void *) command_csucc_or_cfail,    1, 0, 0},
       {AT_COMMAND,    "@damage",                (void *) combat_damage,             0, 0, 0},
       {AT_COMMAND,    "@datefmt",               (void *) set_datetimeformat,        0, 0, 0},
       {AT_COMMAND,    "@dateformat",            (void *) set_datetimeformat,        0, 0, 0},
       {AT_COMMAND,    "@datetimefmt",           (void *) set_datetimeformat,        0, 0, 0},
       {AT_COMMAND,    "@datetimeformat",        (void *) set_datetimeformat,        0, 0, 0},
       {AT_COMMAND,    "@delay",                 (void *) combat_delay,              0, 0, 0},
       {AT_COMMAND,    "@desc",                  (void *) set_description,           0, 0, 0},
       {AT_COMMAND,    "@describe",              (void *) set_description,           0, 0, 0},
       {AT_COMMAND,    "@description",           (void *) set_description,           0, 0, 0},
       {AT_COMMAND,    "@describetemp",          (void *) temp_describe,             0, 0, 0},
       {AT_COMMAND,    "@describetemporary",     (void *) temp_describe,             0, 0, 0},
       {AT_COMMAND,    "@desctemp",              (void *) temp_describe,             0, 0, 0},
       {AT_COMMAND,    "@desctemporary",         (void *) temp_describe,             0, 0, 0},
       /* Commented out because there's a bug when creating a ton of items then
	  destroying them, for the moment, all destroys are now purges */
       /* {AT_COMMAND,    "@dest",                  (void *) destroy_destroy,           0, 0, 0}, */
       {AT_COMMAND,    "@dest",                  (void *) destroy_destroy,
	1, 0, 0},
       {AT_COMMAND,    "@destall",               (void *) destroy_destroyall,        0, 0, 0},
       /* Same as above, all destroys are now purges (put back to 0, 0, 0 for
	  old (dangerous) behaviour */
       {AT_COMMAND,    "@destroy",               (void *) destroy_destroy,           1, 0, 0},
       {AT_COMMAND,    "@destroyall",            (void *) destroy_destroyall,        0, 0, 0},
       {AT_COMMAND,    "@destroytemp",           (void *) temp_destroy,              0, 0, 0},
       {AT_COMMAND,    "@destroytemporary",      (void *) temp_destroy,              0, 0, 0},
       {AT_COMMAND,    "@desttemp",              (void *) temp_destroy,              0, 0, 0},
       {AT_COMMAND,    "@desttemporary",         (void *) temp_destroy,              0, 0, 0},
       {AT_COMMAND,    "@dig",                   (void *) create_room,               0, 0, 0},
       {AT_COMMAND,    "@drop",                  (void *) set_drop,                  0, 0, 0},
       {AT_COMMAND,    "@dump",                  (void *) admin_dump,                0, 0, 0},
       {AT_COMMAND,    "@dup",                   (void *) create_duplicate,          0, 0, 0},
       {AT_COMMAND,    "@duplicate",             (void *) create_duplicate,          0, 0, 0},
       {AT_COMMAND,    "@echo",                  (void *) comms_echo,                0, 0, 0},
       {AT_COMMAND,    "@echolist",              (void *) comms_echolist,            0, 0, 0},
       {AT_COMMAND,    "@else",                  (void *) selection_else,            0, 0, 0},
       {AT_COMMAND,    "@email",                 (void *) set_email,                 0, 0, 0},
       {AT_COMMAND,    "@en",                    (void *) search_entrances,          0, 0, 0},
       {AT_COMMAND,    "@end",                   (void *) selection_end,             0, 0, 0},
       {AT_COMMAND,    "@entrances",             (void *) search_entrances,          0, 0, 0},
       {QUERY_COMMAND, "@eval",                  (void *) calculate_evaluate,        0, 0, 0},
       {QUERY_COMMAND, "@evaluate",              (void *) calculate_evaluate,        0, 0, 0},
       {AT_COMMAND,    "@execution",             (void *) command_executionlimit,    0, 0, 0},
       {AT_COMMAND,    "@executionlimit",        (void *) command_executionlimit,    0, 0, 0},
       {AT_COMMAND,    "@exit",                  (void *) create_exit,               0, 0, 0},
       {AT_COMMAND,    "@expiry",                (void *) set_expiry,                0, 0, 0},
       {AT_COMMAND,    "@estr",                  (void *) set_estring,               0, 0, 0},
       {AT_COMMAND,    "@estring",               (void *) set_estring,               0, 0, 0},
       {AT_COMMAND,    "@fail",                  (void *) set_fail,                  0, 0, 0},
       {AT_COMMAND,    "@failure",               (void *) set_fail,                  0, 0, 0},
       {QUERY_COMMAND, "@false",                 (void *) command_true_or_false,     0, 0, 0},
       {AT_COMMAND,    "@feelings",              (void *) set_feeling,               0, 0, 0},
       {AT_COMMAND,    "@find",                  (void *) search_find,               0, 0, 0},
       {AT_COMMAND,    "@flag",                  (void *) set_flag,                  0, 0, 0},
       {AT_COMMAND,    "@flags",                 (void *) set_flag,                  0, 0, 0},
       {AT_COMMAND,    "@for",                   (void *) selection_for,             0, 0, 0},
       {AT_COMMAND,    "@force",                 (void *) admin_force,               0, 0, 0},
       {AT_COMMAND,    "@foreach",               (void *) selection_foreach,         0, 0, 0},
       {AT_COMMAND,    "@from",                  (void *) search_entrances,          0, 0, 0},
       {AT_COMMAND,    "@fuse",                  (void *) create_fuse,               0, 0, 0},
       {AT_COMMAND,    "@goto",                  (void *) selection_goto,            0, 0, 0},
       {AT_COMMAND,    "@heal",                  (void *) combat_heal,               0, 0, 0},
       {AT_COMMAND,    "@homeroom",              (void *) move_homeroom,             0, 0, 0},
       {AT_COMMAND,    "@if",                    (void *) selection_if,              0, 0, 0},
       {AT_COMMAND,    "@index",                 (void *) array_index,               NOTHING, 0, 0},
       {AT_COMMAND,    "@indexname",             (void *) array_index,               NOTHING, 0, 0},
       {AT_COMMAND,    "@insert",                (void *) array_insert,              0, 0, 0},
       {AT_COMMAND,    "@insertelement",         (void *) array_insert,              0, 0, 0},
       {AT_COMMAND,    "@key",                   (void *) set_key,                   0, 0, 0},
       {AT_COMMAND,    "@link",                  (void *) set_link,                  0, 0, 0},
       {AT_COMMAND,    "@list",                  (void *) search_list,               0, 0, 0},
       {AT_COMMAND,    "@loc",                   (void *) move_teleport,             0, 0, 0},
       {AT_COMMAND,    "@local",                 (void *) temp_describe,             0, 0, 0},
       {AT_COMMAND,    "@localvar",              (void *) temp_describe,             0, 0, 0},
       {AT_COMMAND,    "@localvariable",         (void *) temp_describe,             0, 0, 0},
       {AT_COMMAND,    "@location",              (void *) move_teleport,             0, 0, 0},
       {AT_COMMAND,    "@lock",                  (void *) set_lock,                  0, 0, 0},
       {AT_COMMAND,    "@log",                   (void *) logfile_log,               0, 0, 0},
       {AT_COMMAND,    "@logentry",              (void *) logfile_logentry,          0, 0, 0},
       {AT_COMMAND,    "@logfile",               (void *) logfile_log,               0, 0, 0},
       {AT_COMMAND,    "@mass",                  (void *) set_mass,                  0, 0, 0},
       {AT_COMMAND,    "@mexec",                 (void *) command_true_or_false,     1, 0, 0},
       {AT_COMMAND,    "@mexecute",              (void *) command_true_or_false,     1, 0, 0},
       {AT_COMMAND,    "@monitor",               (void *) admin_monitor,             0, 0, 0},
       {AT_COMMAND|CMD_EXACT, "@maintenance",    (void *) admin_maintenance,         0, 0, 0},
       {AT_COMMAND,    "@name",                  (void *) set_name,                  0, 0, 0},
       {AT_COMMAND,    "@namelowercase",         (void *) set_name,                  1, 0, 0},
       {AT_COMMAND,    "@nat",                   (void *) admin_chat,                0, 0, 0},
       {AT_COMMAND,    "@natter",                (void *) admin_chat,                0, 0, 0},
       {AT_COMMAND,    "@newpassword",           (void *) admin_newpassword,         0, 0, 0},
       {AT_COMMAND,    "@notify",                (void *) comms_notify,              0, 0, 0},
       {AT_COMMAND,    "@oecho",                 (void *) comms_oecho,               0, 0, 0},
       {AT_COMMAND,    "@oemote",                (void *) comms_oemote,              0, 0, 0},
       {AT_COMMAND,    "@ofail",                 (void *) set_ofail,                 0, 0, 0},
       {AT_COMMAND,    "@ofailure",              (void *) set_ofail,                 0, 0, 0},
       {AT_COMMAND,    "@osucc",                 (void *) set_osucc,                 0, 0, 0},
       {AT_COMMAND,    "@osuccess",              (void *) set_osucc,                 0, 0, 0},
       {AT_COMMAND,    "@odrop",                 (void *) set_odrop,                 0, 0, 0},
       {AT_COMMAND,    "@odesc",                 (void *) set_odesc,                 0, 0, 0},
       {AT_COMMAND,    "@odescribe",             (void *) set_odesc,                 0, 0, 0},
       {AT_COMMAND,    "@odescription",          (void *) set_odesc,                 0, 0, 0},
       {AT_COMMAND,    "@open",                  (void *) create_exit,               0, 0, 0},
       {AT_COMMAND,    "@openexit",              (void *) create_exit,               0, 0, 0},
       {AT_COMMAND,    "@owner",                 (void *) set_owner,                 0, 0, 0},
       {AT_COMMAND,    "@ownership",             (void *) set_owner,                 0, 0, 0},
       {AT_COMMAND,    "@output",                (void *) command_output,            0, 0, 0},
       {AT_COMMAND,    "@par",                   (void *) set_parent,                0, 0, 0},
       {AT_COMMAND,    "@parent",                (void *) set_parent,                0, 0, 0},
       {AT_COMMAND,    "@partner",               (void *) admin_partner,             0, 0, 0},
       {AT_COMMAND,    "@password",              (void *) set_password,              0, 0, 0},
       {AT_COMMAND,    "@pay",                   (void *) finance_transaction,       0, 0, 0},
       {AT_COMMAND,    "@pcreate",               (void *) create_character,          0, 0, 0},
       {AT_COMMAND,    "@pending",               (void *) event_pending,             0, 0, 0},
       {AT_COMMAND,    "@prefix",                (void *) set_prefix,                0, 0, 0},
       {AT_COMMAND,    "@pro",                   (void *) set_profile,               0, 0, 0},
       {AT_COMMAND,    "@profile",               (void *) set_profile,               0, 0, 0},
       {AT_COMMAND,    "@prompt",                (void *) prompt_interactive,        0, 0, 0},
       {AT_COMMAND,    "@prop",                  (void *) create_variable_property,  1, 0, 0},
       {AT_COMMAND,    "@property",              (void *) create_variable_property,  1, 0, 0},
       {AT_COMMAND,    "@puppet",                (void *) admin_controller,          0, 0, 0},
       {AT_COMMAND,    "@purge",                 (void *) destroy_destroy,           1, 0, 0},
       {AT_COMMAND,    "@quota",                 (void *) stats_quota,               0, 0, 0},
       {AT_COMMAND,    "@quotalimit",            (void *) admin_quotalimit,          0, 0, 0},
       {AT_COMMAND,    "@race",                  (void *) set_race,                  0, 0, 0},
       {AT_COMMAND,    "@rank",                  (void *) stats_rank,                0, 0, 0},
       {AT_COMMAND,    "@ranks",                 (void *) stats_rank,                0, 0, 0},
       {AT_COMMAND,    "@recursion",             (void *) command_executionlimit,    0, 0, 0},
       {AT_COMMAND,    "@recursionlimit",        (void *) command_executionlimit,    0, 0, 0},
       {AT_COMMAND,    "@reload",                (void *) help_reload,               0, 0, 0},
       {AT_COMMAND,    "@rem",                   (void *) move_remote,               0, 0, 0},
       {AT_COMMAND,    "@remote",                (void *) move_remote,               0, 0, 0},
       {AT_COMMAND,    "@request",               (void *) request_process,           0, 0, 0},
       {AT_COMMAND,    "@restore",               (void *) destroy_undestroy,         0, 0, 0},
       {AT_COMMAND,    "@return",                (void *) selection_return_break,    0, 0, 0},
       {AT_COMMAND,    "@returnval",             (void *) command_returnvalue,       0, 0, 0},
       {AT_COMMAND,    "@returnvalue",           (void *) command_returnvalue,       0, 0, 0},
       {AT_COMMAND,    "@room",                  (void *) create_room,               0, 0, 0},
       {AT_COMMAND,    "@sanitise",              (void *) sanity_main,               0, 0, 0},
       {AT_COMMAND,    "@sanity",                (void *) sanity_main,               0, 0, 0},
       {AT_COMMAND,    "@score",                 (void *) set_score,                 0, 0, 0},
       {AT_COMMAND,    "@set",                   (void *) set_flag,                  0, 0, 0},
       {AT_COMMAND|CMD_EXACT, "@shutdown",       (void *) admin_shutdown,            0, 0, 0},
       {AT_COMMAND,    "@sites",                 (void *) site_process,              0, 0, 0},
       {AT_COMMAND,    "@size",                  (void *) stats_size,                0, 0, 0},
       {AT_COMMAND,    "@skip",                  (void *) selection_skip,            0, 0, 0},
       {AT_COMMAND,    "@sort",                  (void *) array_sort,                0, 0, 0},
       {AT_COMMAND,    "@sortarray",             (void *) array_sort,                0, 0, 0},
       {AT_COMMAND,    "@stats",                 (void *) stats_statistics,          0, 0, 0},
       {AT_COMMAND,    "@statistics",            (void *) stats_statistics,          0, 0, 0},
       {AT_COMMAND,    "@succ",                  (void *) set_succ,                  0, 0, 0},
       {AT_COMMAND,    "@success",               (void *) set_succ,                  0, 0, 0},
       {AT_COMMAND,    "@suffix",                (void *) set_suffix,                0, 0, 0},
       {AT_COMMAND,    "@switch",                (void *) selection_case,            0, 0, 0},
       {AT_COMMAND,    "@switchfirst",           (void *) selection_case,            1, 0, 0},
       {AT_COMMAND,    "@switchrandom",          (void *) selection_case,            2, 0, 0},
       {AT_COMMAND,    "@tel",                   (void *) move_teleport,             0, 0, 0},
       {AT_COMMAND,    "@tele",                  (void *) move_teleport,             0, 0, 0},
       {AT_COMMAND,    "@teleport",              (void *) move_teleport,             0, 0, 0},
       {AT_COMMAND,    "@temp",                  (void *) temp_describe,             0, 0, 0},
       {AT_COMMAND,    "@temporary",             (void *) temp_describe,             0, 0, 0},
       {AT_COMMAND,    "@temporaryvar",          (void *) temp_describe,             0, 0, 0},
       {AT_COMMAND,    "@temporaryvariable",     (void *) temp_describe,             0, 0, 0},
       {AT_COMMAND,    "@test",                  (void *) selection_test,            0, 0, 0},
       {AT_COMMAND,    "@thing",                 (void *) create_thing,              0, 0, 0},
       {AT_COMMAND,    "@timefmt",               (void *) set_datetimeformat,        0, 0, 0},
       {AT_COMMAND,    "@timeformat",            (void *) set_datetimeformat,        0, 0, 0},
       {AT_COMMAND,    "@title",                 (void *) userlist_set_title,        0, 0, 0},
       {AT_COMMAND,    "@transaction",           (void *) finance_transaction,       1, 0, 0},
       {AT_COMMAND,    "@transfer",              (void *) finance_transaction,       1, 0, 0},
       {QUERY_COMMAND, "@true",                  (void *) command_true_or_false,     1, 0, 0},
       {AT_COMMAND,    "@uid",                   (void *) command_chuid,             0, 0, 0},
       {AT_COMMAND,    "@unalias",               (void *) alias_unalias,             0, 0, 0},
       {AT_COMMAND,    "@unaliases",             (void *) alias_unalias,             0, 0, 0},
       {AT_COMMAND,    "@undestroy",             (void *) destroy_undestroy,         0, 0, 0},
       {AT_COMMAND,    "@unerase",               (void *) destroy_undestroy,         0, 0, 0},
       {AT_COMMAND,    "@unremove",              (void *) destroy_undestroy,         0, 0, 0},
       {AT_COMMAND,    "@unchp",                 (void *) command_unchpid,           0, 0, 0},
       {AT_COMMAND,    "@unchpid",               (void *) command_unchpid,           0, 0, 0},
       {AT_COMMAND,    "@unlink",                (void *) set_unlink,                0, 0, 0},
       {AT_COMMAND,    "@unlock",                (void *) set_unlock,                0, 0, 0},
       {AT_COMMAND,    "@var",                   (void *) create_variable_property,  0, 0, 0},
       {AT_COMMAND,    "@variable",              (void *) create_variable_property,  0, 0, 0},
       {AT_COMMAND,    "@vol",                   (void *) set_volume,                0, 0, 0},
       {AT_COMMAND,    "@volume",                (void *) set_volume,                0, 0, 0},
       {AT_COMMAND|CMD_EXACT, "@wall",           (void *) admin_shout,               0, 0, 0},
       {AT_COMMAND,    "@with",                  (void *) selection_with,            0, 0, 0},
       {AT_COMMAND,    "@wh",                    (void *) selection_while,           0, 0, 0},
       {AT_COMMAND,    "@while",                 (void *) selection_while,           0, 0, 0},
       {AT_COMMAND,    "@who",                   (void *) userlist_set_title,        0, 0, 0},
       {AT_COMMAND,    "@whomessage",            (void *) userlist_set_title,        0, 0, 0},
       {AT_COMMAND,    "@whostring",             (void *) userlist_set_title,        0, 0, 0},
       {AT_COMMAND,    "@write",                 (void *) comms_write,               0, 0, 0},
       {AT_COMMAND,    "@www",                   (void *) set_www,                   0, 0, 0},
       {AT_COMMAND,    "@wwwaddress",            (void *) set_www,                   0, 0, 0},
       {AT_COMMAND,    "@wwwhomepage",           (void *) set_www,                   0, 0, 0},
       {AT_COMMAND,    NULL,                     NULL,                               0, 0, 0},
};
