/*

.-----------------------------------------------------------------------------.
| The Chatting Zone (TCZ)                            (C) J.P.Boggis 1993-2004 |
| ~~~~~~~~~~~~~~~~~~~~~~~                            ~~~~~~~~~~~~~~~~~~~~~~~~ |
|-----------------------------------------------------------------------------|
| GENERAL_CMDTABLE.H  -  Table of general commands.                           |
|--------------------------[ Copyright Information ]--------------------------|
| This program is free software; you can redistribute it and/or modify        |
| it under the terms of the GNU General Public License as published by        |
| the Free Software Foundation; either version 2 of the License, or           |
| (at your option) any later version.                                         |
|                                                                             |
| This program is distributed in the hope that it will be useful,             |
| but WITHOUT ANY WARRANTY; without even the implied warranty of              |
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the               |
| GNU General Public License for more details.                                |
|                                                                             |
| You should have received a copy of the GNU General Public License           |
| along with this program; if not, write to the Free Software                 |
| Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA   |
|-----------------------[ Credits & Acknowledgements ]------------------------|
| For full details of authors and contributers to TCZ, please see the files   |
| MODULES and CONTRIBUTERS.  For copyright and license information, please    |
| see LICENSE and COPYRIGHT.                                                  |
|                                                                             |
| Module originally designed and written by:  J.P.Boggis 03/06/1999.          |
|-------------------------[ The Chatting Zone (TCZ) ]-------------------------|
|                For more information about TCZ, please visit:                |
|                   http://www.sourceforge.net/projects/tcz                   |
`-----------------------------------------------------------------------------'

  $Id: general_cmdtable.h,v 1.1.1.1 2004/12/02 17:43:24 jpboggis Exp $

*/


/* ---->  General command table  <---- */
struct cmd_table general_cmds[] = {
       {OTHER_COMMAND, ALT_REMOTE_TOKEN,         (void *) pagetell_send,             1, 1, 0},
       {OTHER_COMMAND, ALT_TELL_TOKEN,           (void *) pagetell_send,             1, 0, 0},
       {OTHER_COMMAND, REMOTE_TOKEN,             (void *) pagetell_send,             1, 1, 0},
       {OTHER_COMMAND, TELL_TOKEN,               (void *) pagetell_send,             1, 0, 0},
       {OTHER_COMMAND, "a",                      (void *) comms_ask,                 0, 0, 0},
       {OTHER_COMMAND, "admin",                  (void *) admin_list,                0, 0, 0},
       {OTHER_COMMAND, "administrating",         (void *) admin_list,                0, 0, 0},
       {OTHER_COMMAND, "administration",         (void *) admin_list,                0, 0, 0},
       {OTHER_COMMAND, "administrators",         (void *) admin_list,                0, 0, 0},
       {OTHER_COMMAND, "adminlisting",           (void *) admin_list,                0, 0, 0},
       {OTHER_COMMAND, "afk",                    (void *) comms_afk,                 0, 0, 0},
       {OTHER_COMMAND, "alias",                  (void *) alias_aliases,             0, 0, 0},
       {OTHER_COMMAND, "aliases",                (void *) alias_aliases,             0, 0, 0},
       {OTHER_COMMAND, "allowtells",             (void *) look_notice,               1, 0, 0},
       {OTHER_COMMAND, "allowpages",             (void *) look_notice,               1, 0, 0},
       {OTHER_COMMAND, "as",                     (void *) comms_ask,                 0, 0, 0},
       {OTHER_COMMAND, "ask",                    (void *) comms_ask,                 0, 0, 0},
       {OTHER_COMMAND, "assist",                 (void *) admin_assist,              0, 0, 0},
       {OTHER_COMMAND, "attr",                   (void *) combat_statistics,         0, 0, 0},
       {OTHER_COMMAND, "attributes",             (void *) combat_statistics,         0, 0, 0},
       {OTHER_COMMAND, "authors",                (void *) modules_authors,           0, 0, 0},
       {OTHER_COMMAND, "back",                   (void *) container_leave,           0, 0, 0},
       {OTHER_COMMAND, "bank",                   (void *) finance_bank,              0, 0, 0},
       {OTHER_COMMAND, "bankroom",               (void *) finance_bank,              0, 0, 0},
       {OTHER_COMMAND, "bbs",                    (void *) bbs_bbs,                   0, 0, 0},
       {OTHER_COMMAND, "bbsroom",                (void *) bbs_bbs,                   0, 0, 0},
       {OTHER_COMMAND, "blocktells",             (void *) look_notice,               1, 0, 0},
       {OTHER_COMMAND, "blockpages",             (void *) look_notice,               1, 0, 0},
       {OTHER_COMMAND, "brieffinger",            (void *) look_scan,                 0, 0, 0},
       {OTHER_COMMAND, "briefscan",              (void *) look_scan,                 0, 0, 0},
       {OTHER_COMMAND, "briefx",                 (void *) look_scan,                 0, 0, 0},
       {OTHER_COMMAND|CMD_EXACT, "bug",          (void *) comms_comment,             3, 0, 0},
       {OTHER_COMMAND|CMD_EXACT, "bugreport",    (void *) comms_comment,             3, 0, 0},
       {OTHER_COMMAND, "c",                      (void *) comms_chat,                0, 0, 0},
       {OTHER_COMMAND, "cashpoint",              (void *) finance_bank,              0, 0, 0},
       {OTHER_COMMAND, "ch",                     (void *) comms_chat,                0, 0, 0},
       {OTHER_COMMAND, "chat",                   (void *) comms_chat,                0, 0, 0},
       {OTHER_COMMAND, "clear",                  (void *) look_cls,                  0, 0, 0},
       {OTHER_COMMAND, "close",                  (void *) container_close,           0, 0, 0},
       {OTHER_COMMAND, "cls",                    (void *) look_cls,                  0, 0, 0},
       {OTHER_COMMAND, "commands",               (void *) look_notice,               0, 9, 0},
       {OTHER_COMMAND|CMD_EXACT, "comment",      (void *) comms_comment,             1, 0, 0},
       {OTHER_COMMAND|CMD_EXACT, "complain",     (void *) comms_comment,             0, 0, 0},
       {OTHER_COMMAND|CMD_EXACT, "complaint",    (void *) comms_comment,             0, 0, 0},
       {OTHER_COMMAND, "conv",                   (void *) comms_converse,            0, 0, 0},
       {OTHER_COMMAND, "converse",               (void *) comms_converse,            0, 0, 0},
       {OTHER_COMMAND, "d",                      (void *) move_getdrop,              0, 0, 0},
       {OTHER_COMMAND, "date",                   (void *) look_date,                 0, 0, 0},
       {OTHER_COMMAND, "dir",                    (void *) look_at,                   1, 0, 0},
       {OTHER_COMMAND, "disc",                   (void *) look_disclaimer,           0, 0, 0},
       {OTHER_COMMAND, "disclaimer",             (void *) look_disclaimer,           0, 0, 0},
       {OTHER_COMMAND, "dr",                     (void *) move_getdrop,              1, 0, 0},
       {OTHER_COMMAND, "drive",                  (void *) move_drive,                0, 0, 0},
       {OTHER_COMMAND, "drop",                   (void *) move_getdrop,              1, 0, 0},
       {OTHER_COMMAND, "e",                      (void *) comms_pose,                0, 0, 0},
       {OTHER_COMMAND, "em",                     (void *) comms_pose,                0, 0, 0},
       {OTHER_COMMAND, "emote",                  (void *) comms_pose,                0, 0, 0},
       {OTHER_COMMAND, "edit",                   (void *) edit_start,                0, 0, 0},
       {OTHER_COMMAND, "editor",                 (void *) edit_start,                0, 0, 0},
       {OTHER_COMMAND, "email",                  (void *) set_email_publicprivate,   0, 0, 0},
       {OTHER_COMMAND, "emaillist",              (void *) userlist_view,             6, 0, 0},
       {OTHER_COMMAND|CMD_EXACT, "emergency",    (void *) comms_emergency,           0, 0, 0},
       {OTHER_COMMAND, "enter",                  (void *) container_enter,           0, 0, 0},
       {OTHER_COMMAND, "escape",                 (void *) admin_escape,              0, 0, 0},
       {OTHER_COMMAND, "escapejail",             (void *) admin_escape,              0, 0, 0},
       {OTHER_COMMAND, "escapeprison",           (void *) admin_escape,              0, 0, 0},
       {OTHER_COMMAND, "events",                 (void *) yearly_event_list,         0, 0, 0},
       {OTHER_COMMAND, "ex",                     (void *) look_examine,              0, 0, 0},
       {OTHER_COMMAND, "examine",                (void *) look_examine,              0, 0, 0},
       {OTHER_COMMAND, "exit",                   (void *) container_leave,           0, 0, 0},
       {OTHER_COMMAND, "f",                      (void *) look_scan,                 2, 0, 0},
       {OTHER_COMMAND, "fadd",                   (void *) friends_add,               0, 0, 0},
       {OTHER_COMMAND, "fc",                     (void *) friends_chat,              0, 0, 0},
       {OTHER_COMMAND, "fchat",                  (void *) friends_chat,              0, 0, 0},
       {OTHER_COMMAND, "fdelete",                (void *) friends_remove,            0, 0, 0},
       {OTHER_COMMAND, "feelings",               (void *) look_notice,               1, 9, 0},
       {OTHER_COMMAND, "ferase",                 (void *) friends_remove,            0, 0, 0},
       {OTHER_COMMAND, "fi",                     (void *) look_scan,                 2, 0, 0},
       {OTHER_COMMAND, "finger",                 (void *) look_scan,                 2, 0, 0},
       {OTHER_COMMAND, "fingerbrief",            (void *) look_scan,                 0, 0, 0},
       {OTHER_COMMAND, "fingerfull",             (void *) look_scan,                 1, 0, 0},
       {OTHER_COMMAND, "flags",                  (void *) look_examine,              1, 0, 0},
       {OTHER_COMMAND, "flist",                  (void *) friends_list,              1, 0, 0},
       {OTHER_COMMAND, "fothers",                (void *) friends_list,              0, 0, 0},
       {OTHER_COMMAND, "fremove",                (void *) friends_remove,            0, 0, 0},
       {OTHER_COMMAND, "friend",                 (void *) friends_cmd,               0, 0, 0},
       {OTHER_COMMAND, "friendadd",              (void *) friends_add,               0, 0, 0},
       {OTHER_COMMAND, "friendchat",             (void *) friends_chat,              0, 0, 0},
       {OTHER_COMMAND, "frienddelete",           (void *) friends_remove,            0, 0, 0},
       {OTHER_COMMAND, "frienderase",            (void *) friends_remove,            0, 0, 0},
       {OTHER_COMMAND, "friendlist",             (void *) friends_list,              1, 0, 0},
       {OTHER_COMMAND, "friendothers",           (void *) friends_list,              0, 0, 0},
       {OTHER_COMMAND, "friendremove",           (void *) friends_remove,            0, 0, 0},
       {OTHER_COMMAND, "friends",                (void *) userlist_view,             10, 0, 0},
       {OTHER_COMMAND, "friendsadd",             (void *) friends_add,               0, 0, 0},
       {OTHER_COMMAND, "friendschat",            (void *) friends_chat,              0, 0, 0},
       {OTHER_COMMAND, "friendsdelete",          (void *) friends_remove,            0, 0, 0},
       {OTHER_COMMAND, "friendserase",           (void *) friends_remove,            0, 0, 0},
       {OTHER_COMMAND, "friendset",              (void *) friends_set,               0, 0, 0},
       {OTHER_COMMAND, "friendslist",            (void *) friends_list,              1, 0, 0},
       {OTHER_COMMAND, "friendsothers",          (void *) friends_list,              0, 0, 0},
       {OTHER_COMMAND, "friendsremove",          (void *) friends_remove,            0, 0, 0},
       {OTHER_COMMAND, "friendsset",             (void *) friends_set,               0, 0, 0},
       {OTHER_COMMAND, "fset",                   (void *) friends_set,               0, 0, 0},
       {OTHER_COMMAND, "fullfinger",             (void *) look_scan,                 1, 0, 0},
       {OTHER_COMMAND, "fullscan",               (void *) look_scan,                 1, 0, 0},
       {OTHER_COMMAND, "fullx",                  (void *) look_scan,                 1, 0, 0},
       {OTHER_COMMAND, "fuserlist",              (void *) userlist_view,             10, 0, 0},
       {OTHER_COMMAND, "fusers",                 (void *) userlist_view,             10, 0, 0},
       {OTHER_COMMAND, "fw",                     (void *) userlist_view,             10, 0, 0},
       {OTHER_COMMAND, "fwhere",                 (void *) userlist_view,             11, 0, 0},
       {OTHER_COMMAND, "fwho",                   (void *) userlist_view,             10, 0, 0},
       {OTHER_COMMAND, "g",                      (void *) move_visit,                0, 0, 0},
       {OTHER_COMMAND, "get",                    (void *) move_getdrop    ,          0, 0, 0},
       {OTHER_COMMAND, "give",                   (void *) move_give,                 0, 0, 0},
       {OTHER_COMMAND, "go",                     (void *) move_visit,                0, 0, 0},
       {OTHER_COMMAND, "goto",                   (void *) move_character,            0, 0, 0},
       {OTHER_COMMAND, "gouser",                 (void *) move_visit,                0, 0, 0},
       {OTHER_COMMAND|CMD_EXACT, "gripe",        (void *) comms_comment,             0, 0, 0},
       {OTHER_COMMAND, "h",                      (void *) help_main,                 0, 0, 0},
       {OTHER_COMMAND, "he",                     (void *) help_main,                 0, 0, 0},
       {OTHER_COMMAND, "help",                   (void *) help_main,                 0, 0, 0},
       {OTHER_COMMAND, "hitells",                (void *) look_notice,               2, 0, 0},
       {OTHER_COMMAND, "hightells",              (void *) look_notice,               2, 0, 0},
       {OTHER_COMMAND, "home",                   (void *) move_character,            0, 1, 0},
       {OTHER_COMMAND, "homeroom",               (void *) move_character,            0, 2, 0},
       {OTHER_COMMAND, "hostlist",               (void *) userlist_view,             3, 0, 0},
       {OTHER_COMMAND, "hosts",                  (void *) userlist_view,             3, 0, 0},
       {OTHER_COMMAND, "i",                      (void *) look_inventory,            0, 0, 0},
       {OTHER_COMMAND, "idle",                   (void *) look_idle,                 0, 0, 0},
       {OTHER_COMMAND, "idletime",               (void *) look_idle,                 0, 0, 0},
       {OTHER_COMMAND, "in",                     (void *) look_inventory,            0, 0, 0},
       {OTHER_COMMAND, "info",                   (void *) look_version,              0, 0, 0},
       {OTHER_COMMAND, "inform",                 (void *) look_notice,               3, 0, 0},
       {OTHER_COMMAND, "information",            (void *) look_version,              0, 0, 0},
       {OTHER_COMMAND, "inv",                    (void *) look_inventory,            0, 0, 0},
       {OTHER_COMMAND, "inventory",              (void *) look_inventory,            0, 0, 0},
       {OTHER_COMMAND, "j",                      (void *) move_visit,                0, 0, 0},
       {OTHER_COMMAND, "jo",                     (void *) move_visit,                0, 0, 0},
       {OTHER_COMMAND, "join",                   (void *) move_visit,                0, 0, 0},
       {OTHER_COMMAND, "joinuser",               (void *) move_visit,                0, 0, 0},
       {OTHER_COMMAND, "junk",                   (void *) move_kick,                 0, 0, 0},
       {OTHER_COMMAND, "junkit",                 (void *) move_kick,                 0, 0, 0},
       {OTHER_COMMAND, "k",                      (void *) move_kick,                 0, 0, 0},
       {OTHER_COMMAND, "ki",                     (void *) move_kick,                 0, 0, 0},
       {OTHER_COMMAND, "kick",                   (void *) move_kick,                 0, 0, 0},
       {OTHER_COMMAND, "l",                      (void *) look_at,                   1, 0, 0},
       {OTHER_COMMAND, "la",                     (void *) bbs_latest,                0, 0, 0},
       {OTHER_COMMAND, "last",                   (void *) userlist_view,             7, 0, 0},
       {OTHER_COMMAND, "laston",                 (void *) stats_rank,                2, 0, 0},
       {OTHER_COMMAND, "lastseen",               (void *) stats_rank,                2, 0, 0},
       {OTHER_COMMAND, "lastcommands",           (void *) userlist_view,             7, 0, 0},
       {OTHER_COMMAND, "latest",                 (void *) bbs_latest,                0, 0, 0},
       {OTHER_COMMAND, "leave",                  (void *) container_leave,           0, 0, 0},
       {OTHER_COMMAND, "lo",                     (void *) look_at,                   1, 0, 0},
       {OTHER_COMMAND, "localwho",               (void *) userlist_view,             5, 0, 0},
       {OTHER_COMMAND, "lock",                   (void *) container_lock,            0, 0, 0},
       {OTHER_COMMAND, "longestspod",            (void *) stats_rank,                3, 0, 0},
       {OTHER_COMMAND, "longspod",               (void *) stats_rank,                3, 0, 0},
       {OTHER_COMMAND, "look",                   (void *) look_at,                   1, 0, 0},
       {OTHER_COMMAND, "lwho",                   (void *) userlist_view,             5, 0, 0},
       {OTHER_COMMAND, "ls",                     (void *) look_at,                   1, 0, 0},
       {OTHER_COMMAND, "lsu",                    (void *) admin_list,                0, 0, 0},
       {OTHER_COMMAND, "m",                      (void *) map_main,                  0, 0, 0},
       {OTHER_COMMAND, "ma",                     (void *) map_main,                  0, 0, 0},
       {OTHER_COMMAND, "map",                    (void *) map_main,                  0, 0, 0},
       {OTHER_COMMAND, "mail",                   (void *) mail_main,                 0, 0, 0},
       {OTHER_COMMAND, "man",                    (void *) help_main,                 0, 0, 0},
       {OTHER_COMMAND, "manual",                 (void *) help_main,                 0, 0, 0},
       {OTHER_COMMAND, "modules",                (void *) modules_modules,           0, 0, 0},
       {QUERY_COMMAND, "more",                   (void *) pager_more,                0, 0, 0},
       {QUERY_COMMAND, "morepager",              (void *) pager_more,                0, 0, 0},
       {OTHER_COMMAND, "motd",                   (void *) look_motd,                 2, 0, 0},
       {OTHER_COMMAND, "move",                   (void *) move_character,            0, 0, 0},
       {OTHER_COMMAND, "n",                      (void *) bbs_news,                  0, 0, 0},
       {OTHER_COMMAND, "nat",                    (void *) admin_chat,                0, 0, 0},
       {OTHER_COMMAND, "natter",                 (void *) admin_chat,                0, 0, 0},
       {OTHER_COMMAND, "ne",                     (void *) bbs_news,                  0, 0, 0},
       {OTHER_COMMAND, "news",                   (void *) bbs_news,                  0, 0, 0},
       {OTHER_COMMAND, "open",                   (void *) container_open,            0, 0, 0},
       {OTHER_COMMAND, "out",                    (void *) container_leave,           0, 0, 0},
       {OTHER_COMMAND, "p",                      (void *) pagetell_send,             0, 0, 0},
       {OTHER_COMMAND, "pa",                     (void *) pagetell_send,             0, 0, 0},
       {OTHER_COMMAND, "page",                   (void *) pagetell_send,             0, 0, 0},
       {OTHER_COMMAND, "pagef",                  (void *) pagetell_friends,          0, 0, 0},
       {OTHER_COMMAND, "pagefriends",            (void *) pagetell_friends,          0, 0, 0},
       {QUERY_COMMAND, "pager",                  (void *) pager_more,                0, 0, 0},
       {OTHER_COMMAND, "pay",                    (void *) finance_transaction,       0, 0, 0},
       {OTHER_COMMAND, "pf",                     (void *) pagetell_friends,          0, 0, 0},
       {OTHER_COMMAND, "pfriends",               (void *) pagetell_friends,          0, 0, 0},
       {OTHER_COMMAND, "prefs",                  (void *) set_preferences,           0, 0, 0},
       {OTHER_COMMAND, "preferences",            (void *) set_preferences,           0, 0, 0},
       {OTHER_COMMAND, "private",                (void *) look_notice,               9, 0, 0},
       {OTHER_COMMAND, "privateemail",           (void *) look_notice,               9, 0, 0},
       {OTHER_COMMAND, "privileges",             (void *) look_privileges,           0, 0, 0},
       {OTHER_COMMAND, "privs",                  (void *) look_privileges,           0, 0, 0},
       {OTHER_COMMAND, "profile",                (void *) look_profile,              0, 0, 0},
       {OTHER_COMMAND, "public",                 (void *) look_notice,               8, 0, 0},
       {OTHER_COMMAND, "publicemail",            (void *) look_notice,               8, 0, 0},
       {OTHER_COMMAND, "put",                    (void *) move_getdrop,              1, 0, 0},
       {OTHER_COMMAND, "q",                      (void *) userlist_view,             10, 0, 0},
       {OTHER_COMMAND, "quserlist",              (void *) userlist_view,             10, 0, 0},
       {OTHER_COMMAND, "qusers",                 (void *) userlist_view,             10, 0, 0},
       {OTHER_COMMAND, "qw",                     (void *) userlist_view,             10, 0, 0},
       {OTHER_COMMAND, "qwho",                   (void *) userlist_view,             10, 0, 0},
       {OTHER_COMMAND, "quit",                   (void *) look_notice,               4, 0, 0},
       {OTHER_COMMAND, "r",                      (void *) look_at,                   0, 0, 0},
       {OTHER_COMMAND, "re",                     (void *) look_at,                   0, 0, 0},
       {OTHER_COMMAND, "read",                   (void *) look_at,                   0, 0, 0},
       {OTHER_COMMAND, "recall",                 (void *) pagetell_recall,           0, 0, 0},
       {OTHER_COMMAND, "rem",                    (void *) command_rem,               0, 0, 0},
       {OTHER_COMMAND, "remote",                 (void *) pagetell_send,             1, 1, 0},
       {OTHER_COMMAND, "repage",                 (void *) pagetell_send,             2, 0, 0},
       {OTHER_COMMAND, "repeat",                 (void *) pagetell_send,             2, 0, 0},
       {OTHER_COMMAND, "reply",                  (void *) pagetell_reply,            0, 0, 0},
       {OTHER_COMMAND|CMD_EXACT, "report",       (void *) comms_comment,             3, 0, 0},
       {OTHER_COMMAND, "resend",                 (void *) pagetell_send,             2, 0, 0},
       {OTHER_COMMAND, "retell",                 (void *) pagetell_send,             2, 0, 0},
       {OTHER_COMMAND, "review",                 (void *) pagetell_recall,           0, 0, 0},
       {OTHER_COMMAND, "ride",                   (void *) move_ride,                 0, 0, 0},
       {OTHER_COMMAND, "rights",                 (void *) look_privileges,           0, 0, 0},
       {OTHER_COMMAND, "rules",                  (void *) look_notice,               2, 9, 0},
       {OTHER_COMMAND, "s",                      (void *) comms_say,                 0, 0, 0},
       {OTHER_COMMAND, "sa",                     (void *) comms_say,                 0, 0, 0},
       {OTHER_COMMAND, "say",                    (void *) comms_say,                 0, 0, 0},
       {OTHER_COMMAND, "scan",                   (void *) look_scan,                 2, 0, 0},
       {OTHER_COMMAND, "scanbrief",              (void *) look_scan,                 0, 0, 0},
       {OTHER_COMMAND, "scanfull",               (void *) look_scan,                 1, 0, 0},
       {OTHER_COMMAND, "score",                  (void *) look_score,                1, 0, 0},
       {OTHER_COMMAND, "screen",                 (void *) set_screenconfig,          0, 0, 0},
       {OTHER_COMMAND, "screenconfig",           (void *) set_screenconfig,          0, 0, 0},
       {OTHER_COMMAND, "screenconfiguration",    (void *) set_screenconfig,          0, 0, 0},
       {OTHER_COMMAND, "screensetup",            (void *) set_screenconfig,          0, 0, 0},
       {OTHER_COMMAND, "set",                    (void *) set_preferences,           0, 0, 0},
       {OTHER_COMMAND, "settings",               (void *) look_examine,              1, 0, 0},
       {OTHER_COMMAND, "sessions",               (void *) comms_session,             0, 0, 0},
       {OTHER_COMMAND, "shortwho",               (void *) userlist_view,             2, 0, 0},
       {OTHER_COMMAND|CMD_EXACT, "shout",        (void *) admin_shout,               0, 0, 0},
       {OTHER_COMMAND, "sitelist",               (void *) userlist_view,             3, 0, 0},
       {OTHER_COMMAND, "sites",                  (void *) userlist_view,             3, 0, 0},
       {OTHER_COMMAND, "socials",                (void *) look_notice,               1, 9, 0},
       {OTHER_COMMAND, "spod",                   (void *) stats_rank,                1, 0, 0},
       {OTHER_COMMAND, "spods",                  (void *) stats_rank,                1, 0, 0},
       {OTHER_COMMAND, "staff",                  (void *) admin_list,                0, 0, 0},
       {OTHER_COMMAND, "stafflisting",           (void *) admin_list,                0, 0, 0},
       {OTHER_COMMAND, "statistics",             (void *) combat_statistics,         0, 0, 0},
       {OTHER_COMMAND, "stats",                  (void *) combat_statistics,         0, 0, 0},
       {OTHER_COMMAND|CMD_EXACT, "suggest",      (void *) comms_comment,             2, 0, 0},
       {OTHER_COMMAND|CMD_EXACT, "suggestion",   (void *) comms_comment,             2, 0, 0},
       {OTHER_COMMAND, "summ",                   (void *) bbs_summary,               0, 0, 0},
       {OTHER_COMMAND, "summary",                (void *) bbs_summary,               0, 0, 0},
       {OTHER_COMMAND, "summarynewmessages",     (void *) bbs_summary,               0, 0, 0},
       {OTHER_COMMAND, "summon",                 (void *) admin_summon,              0, 0, 0},
       {OTHER_COMMAND, "sw",                     (void *) userlist_view,             2, 0, 0},
       {OTHER_COMMAND, "swho",                   (void *) userlist_view,             2, 0, 0},
       {OTHER_COMMAND, "t",                      (void *) pagetell_send,             1, 0, 0},
       {OTHER_COMMAND, "take",                   (void *) move_getdrop,              0, 0, 0},
       {OTHER_COMMAND, "te",                     (void *) pagetell_send,             1, 0, 0},
       {OTHER_COMMAND, "tell",                   (void *) pagetell_send,             1, 0, 0},
       {OTHER_COMMAND, "tellf",                  (void *) pagetell_friends,          1, 0, 0},
       {OTHER_COMMAND, "tellfriends",            (void *) pagetell_friends,          1, 0, 0},
       {OTHER_COMMAND, "testlists",              (void *) lists_test,                0, 0, 0}, /* REMOVE */
       {OTHER_COMMAND, "tf",                     (void *) pagetell_friends,          1, 0, 0},
       {OTHER_COMMAND, "tfriends",               (void *) pagetell_friends,          1, 0, 0},
       {OTHER_COMMAND, "think",                  (void *) comms_think,               0, 0, 0},
       {OTHER_COMMAND, "throw",                  (void *) move_getdrop,              1, 0, 0},
       {OTHER_COMMAND, "time",                   (void *) look_date,                 0, 0, 0},
       {OTHER_COMMAND, "title",                  (void *) userlist_title,            0, 0, 0},
       {OTHER_COMMAND, "titles",                 (void *) look_titles,               0, 0, 0},
       {OTHER_COMMAND, "titlescreens",           (void *) look_titles,               0, 0, 0},
       {OTHER_COMMAND, "to",                     (void *) move_location,             0, 0, 0},
       {OTHER_COMMAND, "toroom",                 (void *) move_location,             0, 0, 0},
       {OTHER_COMMAND, "tolocation",             (void *) move_location,             0, 0, 0},
       {OTHER_COMMAND, "totalspod",              (void *) stats_rank,                1, 0, 0},
       {OTHER_COMMAND, "transaction",            (void *) finance_transaction,       1, 0, 0},
       {OTHER_COMMAND, "transfer",               (void *) finance_transaction,       1, 0, 0},
       {OTHER_COMMAND, "tut",                    (void *) help_main,                 1, 0, 0},
       {OTHER_COMMAND, "tutorial",               (void *) help_main,                 1, 0, 0},
       {OTHER_COMMAND, "tutorials",              (void *) help_main,                 1, 0, 0},
       {OTHER_COMMAND, "u",                      (void *) userlist_view,             1, 0, 0},
       {OTHER_COMMAND, "unlock",                 (void *) container_unlock,          0, 0, 0},
       {OTHER_COMMAND, "uptime",                 (void *) look_uptime,               0, 0, 0},
       {OTHER_COMMAND, "use",                    (void *) command_use,               0, 0, 0},
       {OTHER_COMMAND, "userlist",               (void *) userlist_view,             1, 0, 0},
       {OTHER_COMMAND, "users",                  (void *) userlist_view,             1, 0, 0},
       {OTHER_COMMAND, "v",                      (void *) move_visit,                0, 0, 0},
       {OTHER_COMMAND, "vi",                     (void *) move_visit,                0, 0, 0},
       {OTHER_COMMAND, "visit",                  (void *) move_visit,                0, 0, 0},
       {OTHER_COMMAND, "version",                (void *) look_version,              0, 0, 0},
       {OTHER_COMMAND, "versioninformation",     (void *) look_version,              0, 0, 0},
       {OTHER_COMMAND, "w",                      (void *) userlist_view,             1, 0, 0},
       {OTHER_COMMAND, "wake",                   (void *) comms_wake,                0, 0, 0},
       {OTHER_COMMAND, "wakeup",                 (void *) comms_wake,                0, 0, 0},
       {OTHER_COMMAND, "warp",                   (void *) move_warp,                 0, 0, 0},
       {OTHER_COMMAND, "warn",                   (void *) admin_warn,                0, 0, 0},
       {OTHER_COMMAND, "welcome",                (void *) admin_welcome,             0, 0, 0},
       {OTHER_COMMAND, "wh",                     (void *) userlist_view,             1, 0, 0},
       {OTHER_COMMAND, "where",                  (void *) userlist_view,             4, 0, 0},
       {OTHER_COMMAND, "whereis",                (void *) userlist_view,             4, 0, 0},
       {OTHER_COMMAND, "whisper",                (void *) comms_whisper,             0, 0, 0},
       {OTHER_COMMAND, "who",                    (void *) userlist_view,             1, 0, 0},
       {OTHER_COMMAND, "whois",                  (void *) look_scan,                 2, 0, 0},
       {OTHER_COMMAND, "x",                      (void *) look_scan,                 2, 0, 0},
       {OTHER_COMMAND, "xb",                     (void *) look_scan,                 0, 0, 0},
       {OTHER_COMMAND, "xbrief",                 (void *) look_scan,                 0, 0, 0},
       {OTHER_COMMAND, "xf",                     (void *) look_scan,                 1, 0, 0},
       {OTHER_COMMAND, "xfull",                  (void *) look_scan,                 1, 0, 0},
       {OTHER_COMMAND, "y",                      (void *) comms_yell,                0, 0, 0},
       {OTHER_COMMAND, "ye",                     (void *) comms_yell,                0, 0, 0},
       {OTHER_COMMAND, "yearlyevents",           (void *) yearly_event_list,         0, 0, 0},
       {OTHER_COMMAND, "yell",                   (void *) comms_yell,                0, 0, 0},
       {OTHER_COMMAND, NULL,                     NULL,                               0, 0, 0},
};
